# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Writing your first project with Java 11, Maven and JUnit5

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up OpenJDK 11
      uses: akv-platform/setup-java@update-toolkit-cache
      with:
        distribution: 'adopt-openj9'
        java-version: '11'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
